# Change these first
owner: MarkAlexRC # Your GitHub organization or username, where this repository lives
repo: rcxuptime # The name of this repository

sites:
  - name: ringcx.ringcentral.com/443
    url: ringcx.ringcentral.com
    port: 443
    check: "tcp-ping"
  - name: portal.vacd.biz/443
    url: ringcx.ringcentral.com
    port: 443
    check: "tcp-ping"
  - name: portal.vacd.biz/8081
    url: ringcx.ringcentral.com
    port: 8081
    check: "tcp-ping"
  - name: engage.ringcentral.com/443
    url: ringcx.ringcentral.com
    port: 443
    check: "tcp-ping"
  - name: engage.ringcentral.com/8081
    url: ringcx.ringcentral.com
    port: 8081
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /rcxuptime
  logoUrl: https://avatars.githubusercontent.com/u/6549285?s=40&v=4
  name: "RCX Upptime"
  introTitle: "This page monitors RCX servers listed [here](https://support.ringcentral.com/article-v2/RingCX-network-requirements.html?brand=RingCentral&product=RingCX&language=en_US) and [here](https://support.ringcentral.com/gb/en/network-and-system-requirements/network-requirements/network-requirements-engage-voice.html)"
  introMessage: This is a status page which uses **real-time** data from our GitHub repository. No server — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
